# ========
# GENERAL CONFIG
# ========
# Linux Group name to be maintained
group: "iamusersync"

# If set to false, when a user is removed from the system,
# their home folder will also be deleted
keephomedir: false

# Full path to log file
logfile: "/var/log/iamusersync.log"

# The provider to configure the application for
# and it's properties
provider: "GSUITE"
provider-options:
  # Full path to credentials file
  credentials: "./credentials.json"

  # Custom attribute name to query per user
  customattributekey: "SSHKEY"

  # Admin email used to delegate domain wide OAuth
  # scope authority
  gsuiteadmin: "administrator@tuso.tech"

  # If the domain to query differs from gsuite admin's domain
  #oauthdomain: "tuso.tech"